M48
; DRILL file {KiCad (6.0.2)} date Fri Oct 21 14:00:48 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-21T14:00:48+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X6.6762Y-2.1665
X6.8671Y-2.1665
T2
X6.6644Y-2.0472
X6.8789Y-2.0472
T0
M30
